include(CheckCXXCompilerFlag)

macro(gdextension_w3terrain_options)
  add_library(gdextension_w3terrain_options INTERFACE)

  if(gdextension_w3terrain_ENABLE_ASAN)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
      target_compile_options(gdextension_w3terrain_options INTERFACE -fsanitize=address -fno-omit-frame-pointer)
      target_link_options(gdextension_w3terrain_options INTERFACE -fsanitize=address)
    elseif(MSVC)
      target_compile_options(gdextension_w3terrain_options INTERFACE /fsanitize=address /Zi /INCREMENTAL:NO)
      target_compile_definitions(gdextension_w3terrain_options INTERFACE _DISABLE_VECTOR_ANNOTATION _DISABLE_STRING_ANNOTATION)
      target_link_options(gdextension_w3terrain_options INTERFACE /INCREMENTAL:NO)
    endif()
  endif()

  if(gdextension_w3terrain_ENABLE_IPO)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT result OUTPUT output)
    if(result)
      set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
    else()
      message(SEND_ERROR "IPO is not supported: ${output}")
    endif()
  endif()

  if(gdextension_w3terrain_ENABLE_AVX)
    include(CheckCXXCompilerFlag)
    if(MSVC)
      check_cxx_compiler_flag("/arch:AVX" COMPILER_SUPPORTS_AVX)
      if(COMPILER_SUPPORTS_AVX)
        target_compile_options(gdextension_w3terrain_options INTERFACE /arch:AVX)
      endif()
    else()
      check_cxx_compiler_flag("-mavx" COMPILER_SUPPORTS_AVX)
      if(COMPILER_SUPPORTS_AVX)
        target_compile_options(gdextension_w3terrain_options INTERFACE -mavx)
      endif()
    endif()
  endif()

endmacro()

